version: '3'

services:

  db:
    container_name: db
    image: postgres:14
    env_file:
      - ./.env
    expose:
      - "${POSTGRES_PORT}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: